[phases.setup]
nixPkgs = [
  "python311Full",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "postgresql",
  "python311Packages.psycopg2"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"
