[phases.setup]
nixPkgs = [
  "mariadb-connector-c",
  "pkg-config",
  "postgresql",
  "python311Full",
  "python311Packages.pip",
  "python311Packages.psycopg2",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.build]
commands = [
  "export MYSQLCLIENT_CFLAGS=$(pkg-config --cflags mariadb)",
  "export MYSQLCLIENT_LDFLAGS=$(pkg-config --libs mariadb)",
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]


[phases.install]
cmds = [
  "pip install --no-cache-dir --break-system-packages -r requirements.txt"
]

[start]
cmd = "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"

