[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "libmysqlclient",
  "postgresql"
]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn project.wsgi:application"
