[phases.setup]
nixPkgs = ["python311Full", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python3 -m virtualenv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn project.wsgi:application"
