[phases.setup]
# Instalamos Python con pip y los paquetes necesarios
nixPkgs = [
  "python311Full",       # Python 3.11 completo con pip
  "openssl",
  "libmysqlclient",
  "postgresql",
  "gcc"
]

[phases.install]
# Instalación de dependencias del proyecto
cmds = [
  "python3 -m ensurepip",  # Asegura que pip esté presente
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
# Comando para producción
cmd = "gunicorn project.wsgi:application"

[variables]
PYTHON = "python3"
