[phases.setup]
nixPkgs = ["python311" "libmysqlclient" "openssl" "gcc" "postgresql"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"
