[phases.setup]
nixPkgs = [
  "python311Full",     # Python con pip incluido
  "gcc",
  "libffi",
  "openssl",
  "postgresql",        # si usas PostgreSQL
  "libmysqlclient"     # si usas MySQL
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn project.wsgi:application"
