[phases.setup]
nixPkgs = [
  "python311Full",     # Incluye pip preinstalado
  "openssl",
  "postgresql",
  "gcc",
  "libffi",
  "libmysqlclient"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn project.wsgi:application"

[variables]
PYTHON = "python3"
