# Generated by Django 5.2 on 2025-05-19 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('cuenta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_abonado_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activa'), (2, 'Cancelada'), (3, 'Vencida')], default=1)),
            ],
            options={
                'db_table': 'cuentas_por_pagar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('correo', models.EmailField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'ACTIVO'), (9, 'INACTIVO')], default=1)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipo_documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta', models.ForeignKey(db_column='cuenta_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cuentaporpagar')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.RESTRICT, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tipodocumento'),
        ),
    ]
